
           ? -> Where-Object
           % -> ForEach-Object
           ac -> Add-Content
           cat -> Get-Content
           cd -> Set-Location
           chdir -> Set-Location
           clc -> Clear-Content
           clear -> Clear-Host
           clhy -> Clear-History
           cli -> Clear-Item
           clp -> Clear-ItemProperty
           cls -> Clear-Host
           clv -> Clear-Variable
           cnsn -> Connect-PSSession
           compare -> Compare-Object
           copy -> Copy-Item
           cp -> Copy-Item
           cpi -> Copy-Item
           cpp -> Copy-ItemProperty
           cvpa -> Convert-Path
           dbp -> Disable-PSBreakpoint
           del -> Remove-Item
           diff -> Compare-Object
           dir -> Get-ChildItem
           dnsn -> Disconnect-PSSession
           ebp -> Enable-PSBreakpoint
           echo -> Write-Output
           epal -> Export-
           epcsv -> Export-Csv
           erase -> Remove-Item
           etsn -> Enter-PSSession
           exsn -> Exit-PSSession
           fc -> Format-Custom
           fhx -> Format-Hex                                  7.0.0.0    Microsoft.PowerShell.Utility
           fl -> Format-List
           foreach -> ForEach-Object
           ft -> Format-Table
           fw -> Format-Wide
           gal -> Get-
           gbp -> Get-PSBreakpoint
           gc -> Get-Content
           gcb -> Get-Clipboard                               7.0.0.0    Microsoft.PowerShell.Management
           gci -> Get-ChildItem
           gcm -> Get-Command
           gcs -> Get-PSCallStack
           gdr -> Get-PSDrive
           gerr -> Get-Error
           gh -> Get-Help
           ghy -> Get-History
           gi -> Get-Item
           gin -> Get-ComputerInfo                            7.0.0.0    Microsoft.PowerShell.Management
           gjb -> Get-Job
           gl -> Get-Location
           gm -> Get-Member
           gmo -> Get-Module
           gp -> Get-ItemProperty
           gps -> Get-Process
           gpv -> Get-ItemPropertyValue
           group -> Group-Object
           gsn -> Get-PSSession
           gsv -> Get-Service
           gtz -> Get-TimeZone                                7.0.0.0    Microsoft.PowerShell.Management
           gu -> Get-Unique
           gv -> Get-Variable
           h -> Get-History
           history -> Get-History
           icm -> Invoke-Command
           iex -> Invoke-Expression
           ihy -> Invoke-History
           ii -> Invoke-Item
           ipal -> Import-
           ipcsv -> Import-Csv
           ipmo -> Import-Module
           irm -> Invoke-RestMethod
           iwr -> Invoke-WebRequest
           kill -> Stop-Process
           List -> Get-ChildItem
           ls -> Get-ChildItem
           man -> help
           md -> mkdir
           measure -> Measure-Object
           mi -> Move-Item
           mount -> New-PSDrive
           move -> Move-Item
           mp -> Move-ItemProperty
           mv -> Move-Item
           nal -> New-
           ndr -> New-PSDrive
           ni -> New-Item
           nmo -> New-Module
           nsn -> New-PSSession
           nv -> New-Variable
           ogv -> Out-GridView
           oh -> Out-Host
           popd -> Pop-Location
           ps -> Get-Process
           pushd -> Push-Location
           pwd -> Get-Location
           r -> Invoke-History
           rbp -> Remove-PSBreakpoint
           rcjb -> Receive-Job
           rcsn -> Receive-PSSession
           rd -> Remove-Item
           rdr -> Remove-PSDrive
           ren -> Rename-Item
           ri -> Remove-Item
           rjb -> Remove-Job
           rm -> Remove-Item
           rmdir -> Remove-Item
           rmo -> Remove-Module
           rni -> Rename-Item
           rnp -> Rename-ItemProperty
           rp -> Remove-ItemProperty
           rsn -> Remove-PSSession
           rv -> Remove-Variable
           rvpa -> Resolve-Path
           sajb -> Start-Job
           sal -> Set-
           saps -> Start-Process
           sasv -> Start-Service
           sbp -> Set-PSBreakpoint
           scb -> Set-Clipboard                               7.0.0.0    Microsoft.PowerShell.Management
           select -> Select-Object
           set -> Set-Variable
           shcm -> Show-Command
           si -> Set-Item
           sl -> Set-Location
           sleep -> Start-Sleep
           sls -> Select-String
           sort -> Sort-Object
           sp -> Set-ItemProperty
           spjb -> Stop-Job
           spps -> Stop-Process
           spsv -> Stop-Service
           start -> Start-Process
           stz -> Set-TimeZone                                7.0.0.0    Microsoft.PowerShell.Management
           sv -> Set-Variable
           tee -> Tee-Object
           type -> Get-Content
           uh -> Update-Help
           where -> Where-Object
           wjb -> Wait-Job
           write -> Write-Output

